### ISSUE TITLE
Unrecognized arguments on Ubuntu

### ISSUE THREAD

**Issue by reichaves** [maxharlow/csvmatch#36]
Hi Max
I watched your talk at NICAR21. I'm Reinaldo, from Brazil
Congratulations on the project
I'm using a computer with Ubuntu 20.04 and python 3.8

I tested some commands, but only the first one worked:
csvmatch forbes-billionaires.csv bloomberg-billionaires.csv --fields1 name --fields2 Name > billionaires-in-both.csv

The others always show the error: csvmatch: error: unrecognized arguments

csvmatch cia-world-leaders.csv davos-delegates.csv --fields1 name --fields2 full_name --ignore-case > leaders-at-davos.csv
usage: csvmatch [-h] [-1 FIELDS1 [FIELDS1 ...]] [-2 FIELDS2 [FIELDS2 ...]]
                [FILE1] [FILE2]
csvmatch: error: unrecognized arguments: --ignore-case

csvmatch forbes-billionaires.csv bloomberg-billionaires.csv --fields1 name --fields2 Name --output 1.name 1.rank 2.Rank > billionaires-in-both-ranked.csv
usage: csvmatch [-h] [-1 FIELDS1 [FIELDS1 ...]] [-2 FIELDS2 [FIELDS2 ...]]
                [FILE1] [FILE2]
csvmatch: error: unrecognized arguments: --output 1.name 1.rank 2.Rank

Please, is there any incompatibility with Ubuntu or do I need to install other libraries?
Or did I make some silly mistake?

Best

**Comment by maxharlow** [comment]
Hi Reinaldo, thanks for coming to the session.

This is really odd. Both those commands look completely correct to me, and nothing else should need to be installed. I think you're right, it sounds like it's something about Ubuntu, but unfortunately I don't have easy access to a machine running Ubuntu at the moment.

Could you try running this, and see if it works?

```
csvmatch cia-world-leaders.csv davos-delegates.csv --ignore-case --fields1 name --fields2 full_name > leaders-at-davos.csv
```

My theory is that the fields flags are thinking that `--ignore-case` is the name of a column rather than a field.
