### ISSUE TITLE
Segmentation Fault: 11 when running fuzzy levenshtein

### ISSUE THREAD

**Issue by nicholassewitz** [maxharlow/csvmatch#7]
Hey when I try run csvmatch test1.csv test2.csv --fuzzy levenshtein in the terminal it crashes my terminal and give segmentation fault 11. I am using python 2.7.11. Sometimes it will output results in ther terminal sometimes it won't.

**Comment by maxharlow** [comment]
Looks like this is related to https://github.com/jamesturk/jellyfish/issues/52 and https://github.com/jamesturk/jellyfish/issues/55. I've updated to the latest version of Jellyfish and moved to the Python version of the algorithm (rather than the faster C implementation), which should fix this issue.

Could you try updating to version 1.11 and give it a go with your data?

**Comment by maxharlow** [comment]
Believe this is fixed now
